const subscriptionData = {
	Netflix_Basic: {
		subName: 'Netflix',
		yearlyFrequency: 12,
		price: 8.99,
		type: 'Basic',
	},
	Netflix_Standard: {
		subName: 'Netflix',
		yearlyFrequency: 12,
		price: 13.99,
		type: 'Standard',
	},
	Netflix_Premium: {
		subName: 'Netflix',
		yearlyFrequency: 12,
		price: 17.99,
		type: 'Premium',
	},
	Hulu_Basic: {
		subName: 'Hulu',
		yearlyFrequency: 12,
		price: 5.99,
		type: 'Basic',
	},
	Hulu_NoAds: {
		subName: 'Hulu',
		yearlyFrequency: 12,
		price: 11.99,
		type: 'No Ads',
	},
	Hulu_Basic_and_LiveTV: {
		subName: 'Hulu',
		yearlyFrequency: 12,
		price: 64.99,
		type: 'Basic and Live TV',
	},
	Hulu_No_Ads_and_LiveTV: {
		subName: 'Hulu',
		yearlyFrequency: 12,
		price: 70.99,
		type: 'NoAds and Live TV',
	},
	Peacock_With_Ads: {
		subName: 'Peacock',
		yearlyFrequency: 12,
		price: 4.99,
		type: 'All inclusive with ads',
	},
	Peacock_Without_Ads: {
		subName: 'Peacock',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'All inclusive without ads',
	},
	CBS_All_Access_With_Ads: {
		subName: 'CBS All Access',
		yearlyFrequency: 12,
		price: 5.99,
		type: 'All access with ads',
	},
	CBS_All_Access_Without_Ads: {
		subName: 'CBS All Access',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'All access without ads',
	},
	Apple_TV_Plus: {
		subName: 'Apple TV',
		yearlyFrequency: 12,
		price: 4.99,
		type: 'Plus',
	},
	Disney_Plus: {
		subName: 'Disney Plus',
		yearlyFrequency: 12,
		price: 7.99,
		type: 'Plus',
	},
	HBO_Max: {
		subName: 'HBO Max',
		yearlyFrequency: 12,
		price: 14.99,
		type: 'Standard',
	},
	Sling_TV_Orange: {
		subName: 'Sling TV',
		yearlyFrequency: 12,
		price: 35,
		type: 'Orange',
	},
	Sling_TV_Blue: {
		subName: 'Sling TV',
		yearlyFrequency: 12,
		price: 35,
		type: 'Blue',
	},
	Sling_TV_Orange_and_Blue: {
		subName: 'Sling TV',
		yearlyFrequency: 12,
		price: 50,
		type: 'Orange and Blue',
	},
	FuboTV_Family: {
		subName: 'Fubo',
		yearlyFrequency: 12,
		price: 64.99,
		type: 'Family',
	},
	FuboTV_Elite: {
		subName: 'Fubo',
		yearlyFrequency: 12,
		price: 79.99,
		type: 'Elite',
	},
	Spotify_Individual: {
		subName: 'Spotify Premium',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'Individual',
	},
	Spotify_Duo: {
		subName: 'Spotify Premium',
		yearlyFrequency: 12,
		price: 12.99,
		type: 'Duo',
	},
	Spotify_Family: {
		subName: 'Spotify Premium',
		yearlyFrequency: 12,
		price: 14.99,
		type: 'Family',
	},
	Spotify_Student: {
		subName: 'Spotify Premium',
		yearlyFrequency: 12,
		price: 4.99,
		type: 'Student',
	},
	YouTube_Music: {
		subName: 'YouTube Music',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'Standard',
	},
	Tidal_Premium: {
		subName: 'Tidal',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'Premium',
	},
	Tidal_HiFi: {
		subName: 'Tidal',
		yearlyFrequency: 12,
		price: 19.99,
		type: 'HiFi',
	},
	Tidal_Family_Premium: {
		subName: 'Tidal',
		yearlyFrequency: 12,
		price: 14.99,
		type: 'Family Premium',
	},
	Tidal_Family_HiFi: {
		subName: 'Tidal',
		yearlyFrequency: 12,
		price: 29.99,
		type: 'Family HiFi',
	},
	Apple_Music_Student: {
		subName: 'Apple Music',
		yearlyFrequency: 12,
		price: 4.99,
		type: 'Student',
	},
	Apple_Music_Individual: {
		subName: 'Apple Music',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'Individual',
	},
	Apple_Music_Family: {
		subName: 'Apple Music',
		yearlyFrequency: 12,
		price: 14.99,
		type: 'Family',
	},
	Pandora_Plus: {
		subName: 'Pandora',
		yearlyFrequency: 12,
		price: 4.99,
		type: 'Plus',
	},
	Pandora_Premium: {
		subName: 'Pandora',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'Premium',
	},
	Google_Play_All_Access: {
		subName: 'Google Play',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'All Access',
	},
	Deezer_Premium: {
		subName: 'Deezer',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'Premium',
	},
	Deezer_Family: {
		subName: 'Deezer',
		yearlyFrequency: 12,
		price: 14.99,
		type: 'Family',
	},
	Amazon_Music_Single_Device: {
		subName: 'Amazon Music',
		yearlyFrequency: 12,
		price: 3.99,
		type: 'Single Device',
	},
	Amazon_Music_Prime_Member: {
		subName: 'Amazon Music',
		yearlyFrequency: 12,
		price: 7.99,
		type: 'Prime Member',
	},
	Amazon_Music_Non_Prime_Member: {
		subName: 'Amazon Music',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'Non Prime Member',
	},
	Amazon_Music_Family: {
		subName: 'Amazon Music',
		yearlyFrequency: 12,
		price: 14.99,
		type: 'Family',
	},
	All_Club_Sport_Basic_24Hour: {
		subName: '24 Hour Fitness',
		yearlyFrequency: 12,
		price: 29.99,
		type: 'All Club Sport Basic',
	},
	All_Club_Sport_Commitment_24Hour: {
		subName: '24 Hour Fitness',
		yearlyFrequency: 12,
		price: 39.99,
		type: 'All Club Sport Commitment (18 mos)',
	},
	All_Club_Sport_Loyalty_24Hour: {
		subName: '24 Hour Fitness',
		yearlyFrequency: 12,
		price: 24.99,
		type: 'All Club Sport Loyalty (13-24 mos)',
	},
	All_Club_Super_Sport_Basic_24Hour: {
		subName: '24 Hour Fitness',
		yearlyFrequency: 12,
		price: 44.99,
		type: 'All Club Super Sport Basic',
	},
	All_Club_Super_Sport_Commitment_24Hour: {
		subName: '24 Hour Fitness',
		yearlyFrequency: 12,
		price: 44.99,
		type: 'All Club Super Sport Commitment (18 mos)',
	},
	All_Club_Super_Sport_Loyalty_24Hour: {
		subName: '24 Hour Fitness',
		yearlyFrequency: 12,
		price: 39.99,
		type: 'All Club Super Sport Loyalty (12 mos)',
	},
	One_Club_Basic_24Hour: {
		subName: '24 Hour Fitness',
		yearlyFrequency: 12,
		price: 29.99,
		type: 'One Club Basic',
	},
	One_Club_Commitment_24Hour: {
		subName: '24 Hour Fitness',
		yearlyFrequency: 12,
		price: 29.99,
		type: 'One Club Commitment (12 mos)',
	},
	Planet_Fitness_Classic: {
		subName: 'Planet Fitness',
		yearlyFrequency: 12,
		price: 10,
		type: 'Classic',
	},
	Planet_Fitness_PF_Black_Card: {
		subName: 'Planet Fitness',
		yearlyFrequency: 12,
		price: 22.99,
		type: 'PF Black Card',
	},
	Anytime_Fitness_One_Person: {
		subName: 'Anytime Fitness',
		yearlyFrequency: 12,
		price: 38.99,
		type: 'One Person',
	},
	Anytime_Fitness_Two_People: {
		subName: 'Anytime Fitness',
		yearlyFrequency: 12,
		price: 59.99,
		type: 'Two People',
	},
	Golds_Gym_Single_Club: {
		subName: "Gold's Gym",
		yearlyFrequency: 12,
		price: 49.95,
		type: 'Single Club',
	},
	Golds_Gym_Multi_Club: {
		subName: "Gold's Gym",
		yearlyFrequency: 12,
		price: 54.95,
		type: 'Multi Club',
	},
	Golds_Gym_Platinum_Gold_Club: {
		subName: "Gold's Gym",
		yearlyFrequency: 12,
		price: 59.99,
		type: 'Platinum Gold Club',
	},
	Equinox_One_Club: {
		subName: 'Equinox',
		yearlyFrequency: 12,
		price: 185,
		type: 'One Club',
	},
	Equinox_Multi_Club: {
		subName: 'Equinox',
		yearlyFrequency: 12,
		price: 250,
		type: 'Multi Club',
	},
	LA_Fitness_Multi_Club: {
		subName: 'LA Fitness',
		yearlyFrequency: 12,
		price: 29.99,
		type: 'Multi Club',
	},
	Crunch_Fitness_Base: {
		subName: 'Crunch Fitness',
		yearlyFrequency: 12,
		price: 14.95,
		type: 'Base',
	},
	Crunch_Fitness_Peak: {
		subName: 'Crunch Fitness',
		yearlyFrequency: 12,
		price: 21.95,
		type: 'Peak',
	},
	Crunch_Fitness_Peak_Results: {
		subName: 'Crunch Fitness',
		yearlyFrequency: 12,
		price: 29.95,
		type: 'Peak Results',
	},
	Orangetheory_Basic: {
		subName: 'Orangetheory Fitness',
		yearlyFrequency: 12,
		price: 59,
		type: 'Basic',
	},
	Orangetheory_Elite: {
		subName: 'Orangetheory Fitness',
		yearlyFrequency: 12,
		price: 99,
		type: 'Elite',
	},
	Orangetheory_Premier: {
		subName: 'Orangetheory Fitness',
		yearlyFrequency: 12,
		price: 159,
		type: 'Premier',
	},
	Peloton_All_Access: {
		subName: 'Peloton',
		yearlyFrequency: 12,
		price: 39,
		type: 'All Access',
	},
	Peloton_Digital_Membership: {
		subName: 'Peloton',
		yearlyFrequency: 12,
		price: 12.99,
		type: 'Digital Membership',
	},
	Amazon_Luna: {
		subName: 'Amazon Gaming',
		yearlyFrequency: 12,
		price: 6,
		type: 'Standard',
	},
	Apple_Arcade: {
		subName: 'Amazon Gaming',
		yearlyFrequency: 12,
		price: 5,
		type: 'Standard',
	},
	Google_Stadia: {
		subName: 'Amazon Gaming',
		yearlyFrequency: 12,
		price: 10,
		type: 'Pro',
	},
	XBOX_Game_Pass_PC: {
		subName: 'XBOX',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'PC/Console',
	},
	XBOX_Game_Pass_Ultimate: {
		subName: 'XBOX',
		yearlyFrequency: 12,
		price: 14.99,
		type: 'Ultimate',
	},
	Nintendo_Switch_Online: {
		subName: 'Nintendo Switch',
		yearlyFrequency: 12,
		price: 4,
		type: 'Standard',
	},
	PlayStation_Plus: {
		subName: 'PlayStation',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'Plus',
	},
	FabFitFun: {
		subName: 'FabFitFun',
		yearlyFrequency: 4,
		price: 49.99,
		type: 'Standard',
	},
	BeSpoke_Post: {
		subName: 'BeSpoke Post',
		yearlyFrequency: 12,
		price: 45,
		type: 'Standard',
	},
	KiwiCo: {
		subName: 'KiwiCo',
		yearlyFrequency: 12,
		price: 19.95,
		type: 'Standard',
	},
	KiwiCo_6mos: {
		subName: 'KiwiCo',
		yearlyFrequency: 12,
		price: 18.5,
		type: '6 months',
	},
	KiwiCo_12mos: {
		subName: 'KiwiCo',
		yearlyFrequency: 12,
		price: 16.95,
		type: '12 months',
	},
	KiwiCo_24mos: {
		subName: 'KiwiCo',
		yearlyFrequency: 12,
		price: 15.5,
		type: '24 months',
	},
	IPSY_Glam_Bag: {
		subName: 'IPSY',
		yearlyFrequency: 12,
		price: 12,
		type: 'Glam Bag',
	},
	IPSY_Glam_Bag_Plus: {
		subName: 'IPSY',
		yearlyFrequency: 12,
		price: 25,
		type: 'Glam Bag Plus',
	},
	IPSY_Combined: {
		subName: 'IPSY',
		yearlyFrequency: 12,
		price: 37,
		type: 'Combined',
	},
	Fabletics_VIP: {
		subName: 'Fabletics',
		yearlyFrequency: 12,
		price: 45,
		type: 'VIP',
	},
	Rocksbox: {
		subName: 'Rocksbox',
		yearlyFrequency: 12,
		price: 21,
		type: 'Standard',
	},
	Barkbox: {
		subName: 'Barkbox',
		yearlyFrequency: 12,
		price: 29,
		type: 'Standard',
	},
	CatLadyBox: {
		subName: 'CatLadyBox',
		yearlyFrequency: 12,
		price: 34.99,
		type: 'Standard',
	},
	Scentbird_1item: {
		subName: 'Scentbird',
		yearlyFrequency: 12,
		price: 14.95,
		type: '1 item',
	},
	Scentbird_2items: {
		subName: 'Scentbird',
		yearlyFrequency: 12,
		price: 25,
		type: '2 items',
	},
	Scentbird_3items: {
		subName: 'Scentbird',
		yearlyFrequency: 12,
		price: 35,
		type: '3 items',
	},
	Dollar_Shave_Club: {
		subName: 'Dollar Shave Club',
		yearlyFrequency: 12,
		price: 39.6,
		type: 'Standard',
	},
	Hello_Fresh_2people_2recipes: {
		subName: 'Hello Fresh',
		yearlyFrequency: 53,
		price: 58.95,
		type: '2 people 2 recipes',
	},
	Hello_Fresh_2people_3recipes: {
		subName: 'Hello Fresh',
		yearlyFrequency: 53,
		price: 62.93,
		type: '2 people 3 recipes',
	},
	Hello_Fresh_2people_4recipes: {
		subName: 'Hello Fresh',
		yearlyFrequency: 53,
		price: 80.91,
		type: '2 people 4 recipes',
	},
	Hello_Fresh_2people_5recipes: {
		subName: 'Hello Fresh',
		yearlyFrequency: 53,
		price: 98.89,
		type: '2 people 5 recipes',
	},
	Hello_Fresh_4people_2recipes: {
		subName: 'Hello Fresh',
		yearlyFrequency: 53,
		price: 80.91,
		type: '4 people 2 recipes',
	},
	Hello_Fresh_4people_3recipes: {
		subName: 'Hello Fresh',
		yearlyFrequency: 53,
		price: 98.87,
		type: '4 people 3 recipes',
	},
	Hello_Fresh_4people_4recipes: {
		subName: 'Hello Fresh',
		yearlyFrequency: 53,
		price: 128.83,
		type: '4 people 4 recipes',
	},
	Sun_Basket_2meals_2servings: {
		subName: 'Sun Basket',
		yearlyFrequency: 53,
		price: 55.96,
		type: '2 meals 2 servings',
	},
	Sun_Basket_2meals_4servings: {
		subName: 'Sun Basket',
		yearlyFrequency: 53,
		price: 87.92,
		type: '2 meals 4 servings',
	},
	Sun_Basket_3meals_2servings: {
		subName: 'Sun Basket',
		yearlyFrequency: 53,
		price: 71.94,
		type: '3 meals 2 servings',
	},
	Sun_Basket_3meals_4servings: {
		subName: 'Sun Basket',
		yearlyFrequency: 53,
		price: 131.88,
		type: '3 meals 4 servings',
	},
	Sun_Basket_4meals_2servings: {
		subName: 'Sun Basket',
		yearlyFrequency: 53,
		price: 87.92,
		type: '4 meals 2 servings',
	},
	Sun_Basket_4meals_4servings: {
		subName: 'Sun Basket',
		yearlyFrequency: 53,
		price: 175.84,
		type: '4 meals 4 servings',
	},
	Blue_Apron_2recipes: {
		subName: 'Blue Apron',
		yearlyFrequency: 53,
		price: 47.95,
		type: '2 recipes',
	},
	Blue_Apron_3recipes: {
		subName: 'Blue Apron',
		yearlyFrequency: 53,
		price: 59.94,
		type: '3 recipes',
	},
	Blue_Apron_4recipes: {
		subName: 'Blue Apron',
		yearlyFrequency: 53,
		price: 79.94,
		type: '4 recipes',
	},
	Blue_Apron_signature4_2recipes: {
		subName: 'Blue Apron',
		yearlyFrequency: 53,
		price: 71.92,
		type: 'Signature for 4, 2 recipes',
	},
	Blue_Apron_signature4_3recipes: {
		subName: 'Blue Apron',
		yearlyFrequency: 53,
		price: 95.88,
		type: 'Signature for 4, 3 recipes',
	},
	Blue_Apron_signature4_4recipes: {
		subName: 'Blue Apron',
		yearlyFrequency: 53,
		price: 119.84,
		type: 'Signature for 4, 4 recipes',
	},
	Yumble_6meals: {
		subName: 'Yumble',
		yearlyFrequency: 53,
		price: 47.94,
		type: '6 meals',
	},
	Yumble_8meals: {
		subName: 'Yumble',
		yearlyFrequency: 53,
		price: 55.92,
		type: '8 meals',
	},
	Yumble_12meals: {
		subName: 'Yumble',
		yearlyFrequency: 53,
		price: 71.88,
		type: '12 meals',
	},
	Snap_Kitchen_6meals: {
		subName: 'Snap Kitchen',
		yearlyFrequency: 53,
		price: 69.99,
		type: '6 meals',
	},
	Snap_Kitchen_12meals: {
		subName: 'Snap Kitchen',
		yearlyFrequency: 53,
		price: 114.99,
		type: '12 meals',
	},
	Home_Chef: {
		subName: 'Home Chef',
		yearlyFrequency: 53,
		price: 49.95,
		type: 'Standard',
	},
	Freshly_4meals: {
		subName: 'Freshly',
		yearlyFrequency: 53,
		price: 49.99,
		type: '4 meals',
	},
	Freshly_6meals: {
		subName: 'Freshly',
		yearlyFrequency: 53,
		price: 59.99,
		type: '6 meals',
	},
	Freshly_9meals: {
		subName: 'Freshly',
		yearlyFrequency: 53,
		price: 89.99,
		type: '9 meals',
	},
	Gobble_6meals: {
		subName: 'Gobble',
		yearlyFrequency: 53,
		price: 78.93,
		type: '6 meals',
	},
	Gobble_8meals: {
		subName: 'Gobble',
		yearlyFrequency: 53,
		price: 102.91,
		type: '8 meals',
	},
	Gobble_12meals: {
		subName: 'Gobble',
		yearlyFrequency: 53,
		price: 150.87,
		type: '12 meals',
	},
	Gobble_16meals: {
		subName: 'Gobble',
		yearlyFrequency: 53,
		price: 198.83,
		type: '16 meals',
	},
	Purple_Carrot_2servings_3dinners: {
		subName: 'Purple Carrot',
		yearlyFrequency: 53,
		price: 71.94,
		type: '2 servings 3 dinners',
	},
	Purple_Carrot_2servings_4dinners: {
		subName: 'Purple Carrot',
		yearlyFrequency: 53,
		price: 95.92,
		type: '2 servings 4 dinners',
	},
	Purple_Carrot_4servings_2dinners: {
		subName: 'Purple Carrot',
		yearlyFrequency: 53,
		price: 79.92,
		type: '4 servings 2 dinners',
	},
	Purple_Carrot_4servings_3dinners: {
		subName: 'Purple Carrot',
		yearlyFrequency: 53,
		price: 119.88,
		type: '4 servings 3 dinners',
	},
	Omaha_Steaks_Monthly: {
		subName: 'Omaha Steaks',
		yearlyFrequency: 12,
		price: 129.99,
		type: 'Monthly Steak Box',
	},
	Omaha_Steaks_Bimonthly: {
		subName: 'Omaha Steaks',
		yearlyFrequency: 6,
		price: 149.99,
		type: 'Bi-Monthly Steak Box',
	},
	Omaha_Steaks_Quarterly: {
		subName: 'Omaha Steaks',
		yearlyFrequency: 4,
		price: 169.99,
		type: 'Quarterly Steak Box',
	},
	DoorDash: {
		subName: 'DoorDash',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'Standard',
	},
	UberEats_Eats_Pass: {
		subName: 'Uber Eats',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'Eats Pass',
	},
	SurfShark_6mos: {
		subName: 'SurfShark',
		yearlyFrequency: 12,
		price: 6.49,
		type: '6 months',
	},
	SurfShark_24mos: {
		subName: 'SurfShark',
		yearlyFrequency: 12,
		price: 2.49,
		type: '24 months',
	},
	NordVPN_1year: {
		subName: 'NordVPN',
		yearlyFrequency: 12,
		price: 4.92,
		type: '1 year',
	},
	NordVPN_2years: {
		subName: 'NordVPN',
		yearlyFrequency: 12,
		price: 3.71,
		type: '2 year',
	},
	ExpressVPN_6mos: {
		subName: 'ExpressVPN',
		yearlyFrequency: 12,
		price: 9.99,
		type: '6 months',
	},
	ExpressVPN_12mos: {
		subName: 'ExpressVPN',
		yearlyFrequency: 12,
		price: 8.32,
		type: '12 months',
	},
	CyberGhost_1year: {
		subName: 'CyberGhost',
		yearlyFrequency: 12,
		price: 3.99,
		type: '1 year',
	},
	CyberGhost_2years: {
		subName: 'CyberGhost',
		yearlyFrequency: 12,
		price: 3.49,
		type: '2 years',
	},
	CyberGhost_3years: {
		subName: 'CyberGhost',
		yearlyFrequency: 12,
		price: 2.25,
		type: '3 years',
	},
	Norton_Antivirus_Basic: {
		subName: 'Norton',
		yearlyFrequency: 1,
		price: 59.99,
		type: 'Antivirus Basic',
	},
	Norton_Security_Standard: {
		subName: 'Norton',
		yearlyFrequency: 1,
		price: 84.99,
		type: 'Security Standard',
	},
	Norton_Security_Deluxe: {
		subName: 'Norton',
		yearlyFrequency: 1,
		price: 94.99,
		type: 'Security Deluxe',
	},
	Norton_Security_Premium: {
		subName: 'Norton',
		yearlyFrequency: 1,
		price: 124.99,
		type: 'Security Premium',
	},
	McAfee_Single_Device: {
		subName: 'McAfee',
		yearlyFrequency: 1,
		price: 79.99,
		type: 'Single Device',
	},
	McAfee_Individual: {
		subName: 'McAfee',
		yearlyFrequency: 1,
		price: 99.99,
		type: 'Individual',
	},
	McAfee_Family: {
		subName: 'McAfee',
		yearlyFrequency: 1,
		price: 119.99,
		type: 'Family',
	},
	McAfee_Ultimate: {
		subName: 'McAfee',
		yearlyFrequency: 1,
		price: 159.99,
		type: 'Ultimate',
	},
	Amazon_Prime: {
		subName: 'Amazon Prime',
		yearlyFrequency: 12,
		price: 12.99,
		type: 'Standard',
	},
	Audible_Plus: {
		subName: 'Audible',
		yearlyFrequency: 12,
		price: 7.95,
		type: 'Plus',
	},
	Audible_Premium_Plus: {
		subName: 'Audible',
		yearlyFrequency: 12,
		price: 14.95,
		type: 'Premium Plus',
	},
	Tinder_Gold_1month: {
		subName: 'Tinder',
		yearlyFrequency: 12,
		price: 14.99,
		type: 'Gold 1 month',
	},
	Tinder_Gold_6months: {
		subName: 'Tinder',
		yearlyFrequency: 12,
		price: 8.83,
		type: 'Gold 6 months',
	},
	Tinder_Gold_12months: {
		subName: 'Tinder',
		yearlyFrequency: 12,
		price: 6.92,
		type: 'Gold 12 months',
	},
	Tinder_Plus_1month: {
		subName: 'Tinder',
		yearlyFrequency: 12,
		price: 4.99,
		type: 'Plus 1 month',
	},
	Tinder_Plus_6months: {
		subName: 'Tinder',
		yearlyFrequency: 12,
		price: 3,
		type: 'Plus 6 months',
	},
	Tinder_Plus_12months: {
		subName: 'Tinder',
		yearlyFrequency: 12,
		price: 2.33,
		type: 'Plus 12 months',
	},
	Bumble_Boost: {
		subName: 'Bumble',
		yearlyFrequency: 12,
		price: 14.99,
		type: 'Boost',
	},
	Bumble_Premium: {
		subName: 'Bumble',
		yearlyFrequency: 12,
		price: 32.99,
		type: 'Premium',
	},
	Microsoft_365_Personal: {
		subName: 'Microsoft',
		yearlyFrequency: 1,
		price: 69.99,
		type: '365 Personal',
	},
	Microsoft_365_Family: {
		subName: 'Microsoft',
		yearlyFrequency: 1,
		price: 99.99,
		type: '365 Family',
	},
	Adobe_All_Apps: {
		subName: 'Adobe',
		yearlyFrequency: 12,
		price: 52.99,
		type: 'All Apps',
	},
	Adobe_XD: {
		subName: 'Adobe',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'XD',
	},
	Adobe_Photoshop: {
		subName: 'Adobe',
		yearlyFrequency: 12,
		price: 20.99,
		type: 'Photoshop',
	},
	Adobe_Illustrator: {
		subName: 'Adobe',
		yearlyFrequency: 12,
		price: 20.99,
		type: 'Illustrator',
	},
	Adobe_After_Effects: {
		subName: 'Adobe',
		yearlyFrequency: 12,
		price: 20.99,
		type: 'After Effects',
	},
	Adobe_Premiere_Pro: {
		subName: 'Adobe',
		yearlyFrequency: 12,
		price: 20.99,
		type: 'Premiere Pro',
	},
	Adobe_Lightroom: {
		subName: 'Adobe',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'Lightroom',
	},
	Adobe_inDesign: {
		subName: 'Adobe',
		yearlyFrequency: 12,
		price: 20.99,
		type: 'inDesign',
	},
	Adobe_Acrobat_Pro: {
		subName: 'Adobe',
		yearlyFrequency: 12,
		price: 14.99,
		type: 'Acrobat Pro',
	},
	Adobe_Dreamweaver: {
		subName: 'Adobe',
		yearlyFrequency: 12,
		price: 20.99,
		type: 'Acrobat Pro',
	},
	Adobe_Stock: {
		subName: 'Adobe',
		yearlyFrequency: 12,
		price: 29.99,
		type: 'Stock',
	},
	WordPress_Personal: {
		subName: 'WordPress',
		yearlyFrequency: 1,
		price: 48,
		type: 'Personal',
	},
	WordPress_Premium: {
		subName: 'WordPress',
		yearlyFrequency: 1,
		price: 96,
		type: 'Premium',
	},
	WordPress_Business: {
		subName: 'WordPress',
		yearlyFrequency: 1,
		price: 300,
		type: 'Business',
	},
	WordPress_eCommerce: {
		subName: 'WordPress',
		yearlyFrequency: 1,
		price: 540,
		type: 'eCommerce',
	},
	BlueHost_Shared_Hosting: {
		subName: 'BlueHost',
		yearlyFrequency: 12,
		price: 3.95,
		type: 'Shared Hosting',
	},
	BlueHost_VPS: {
		subName: 'BlueHost',
		yearlyFrequency: 12,
		price: 19.99,
		type: 'VPS',
	},
	BlueHost_Dedicated: {
		subName: 'BlueHost',
		yearlyFrequency: 12,
		price: 79.99,
		type: 'Dedicated',
	},
	GoDaddy_Basic: {
		subName: 'GoDaddy',
		yearlyFrequency: 12,
		price: 9.99,
		type: 'Basic',
	},
	GoDaddy_Standard: {
		subName: 'GoDaddy',
		yearlyFrequency: 12,
		price: 14.99,
		type: 'Standard',
	},
	GoDaddy_Premium: {
		subName: 'GoDaddy',
		yearlyFrequency: 12,
		price: 19.99,
		type: 'Premium',
	},
	GoDaddy_eCommerce: {
		subName: 'GoDaddy',
		yearlyFrequency: 12,
		price: 24.99,
		type: 'eCommerce',
	},
}

export default subscriptionData